import { ParkingFields } from "./ParkingsOverview.types";

export const PARKING_CONST: ParkingFields = {
  totalcapacity_test: 1,
  open: "True",
  id: "string",
  from: "string",
  daysopen: "string",
  openingtimes: "string",
  to: "string",
  latitude: "string",
  parkingserver: "string",
  contactinfo: "string",
  description: "fake",
  city: "Gent",
  suggestedfreethreshold: 4,
  capacityrounding: 100,
  availablecapacity: 75,
  address: "Haagstuk 47",
  newopeningtimes: "string",
  name: "Fake parking",
  longitude: 1,
  suggestedcapacity: "string",
  parkingstatus: "string",
  totalcapacity: 100,
  lastmodifieddate: new Date(),
  lastupdate: new Date(),
  suggestedfullthreshold: 4,
  geo_location: [1, 1],
};
